# Example configuration file
# 
ip_addr = "0.0.0.0:8080"
data_dir = "/var/lib/storage"
domain = "https://storage.example.com"
ttl_orphan_secs = 43200           # 12 h
max_data_rq_size = 4294967296     # 4 GiB
max_presign_rq_size = 102400      # 100 KiB
rq_timeout_secs = 30
